<?php
/**
 * Created by PhpStorm.
 *
 * 
 *
 * Date: 2021/5/26
 * Time: 11:20
 */

namespace app\frontend\modules\cart\deduction\models;


use app\frontend\modules\cart\models\CartBaseModel;
use app\frontend\modules\cart\models\CartGoods;

class PreCartGoodsDeduction  extends CartBaseModel
{
     public $cartGoods;

     public function setCartGoods(CartGoods $cartGoods)
     {
         $this->cartGoods = $cartGoods;

         $this->cartGoods->getCartGoodsDeductions()->push($this);

     }

     public function toArray()
     {

         $this->amount = sprintf('%.2f', $this->amount);
         return parent::toArray(); // TODO: Change the autogenerated stub
     }
 }
