<?php
/**
 * Created by PhpStorm.
 * Name: 芸众商城系统
 * Author: 广州市芸众信息科技有限公司
 * Profile: 广州市芸众信息科技有限公司位于国际商贸中心的广州，专注于移动电子商务生态系统打造，拥有芸众社交电商系统、区块链数字资产管理系统、供应链管理系统、电子合同等产品/服务。官网 ：www.yunzmall.com  www.yunzshop.com
 * Date: 2021/5/26
 * Time: 11:20
 */

namespace app\frontend\modules\cart\deduction\models;


use app\frontend\modules\cart\models\CartBaseModel;
use app\frontend\modules\cart\models\CartGoods;

class PreCartGoodsDeduction  extends CartBaseModel
{
     public $cartGoods;

     public function setCartGoods(CartGoods $cartGoods)
     {
         $this->cartGoods = $cartGoods;

         $this->cartGoods->getCartGoodsDeductions()->push($this);

     }

     public function toArray()
     {

         $this->amount = sprintf('%.2f', $this->amount);
         return parent::toArray(); // TODO: Change the autogenerated stub
     }
 }
