<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2020/8/3
 * Time: 9:50
 */

namespace app\frontend\modules\order\dispatch\order;


use app\common\exceptions\AppException;

class ExpressOrderDispatchType extends BaseOrderDispatchType
{
    public function _init()
    {
        //$this->verifyAddress();
    }

    public function verifyAddress()
    {
        $address = json_decode(urldecode($this->order->getRequest()->input('address', '[]')), true);

        $this->validateInfo($address);

    }

    public function validateInfo($request = null)
    {

        $rules = [
            'address' => 'required',
            'mobile' => 'required',
            'username' => 'required',
            //province' => 'required',
            //'city' => 'required',
            // 'zipcode' => '',
            //'district' => 'required'
        ];

        $customAttributes = [
            'address' => '详细地址',
            'mobile' => '联系方式',
            'username' => '收件人',
        ];

        $validator = $this->getValidationFactory()->make($request, $rules, [],$customAttributes);

        if ($validator->fails()) {
            throw new AppException($validator->errors()->first());
        }
    }

    public function preOrderAddress()
    {
        return parent::preOrderAddress(); // TODO: Change the autogenerated stub
    }
}