<?php

namespace app\common\components;

use app\common\exceptions\AppException;

use app\common\exceptions\ShopException;
use app\common\middleware\BasicInformation;
use app\common\middleware\SingleLogin;
use app\common\services\Check;
use app\common\services\PermissionService;
use app\common\services\Session;

use app\common\services\Utils;
use app\common\traits\JsonTrait;
use app\common\traits\MessageTrait;
use app\common\traits\PermissionTrait;
use app\common\traits\TemplateTrait;
use app\platform\modules\system\models\SystemSetting;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Cookie;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;

/**
 * controller基类
 *
 * Author: 芸众商城 www.yunzshop.com
 * Date: 21/02/2017
 * Time: 21:20
 */
class BaseController extends Controller
{
    use DispatchesJobs, MessageTrait, ValidatesRequests, TemplateTrait, PermissionTrait, JsonTrait;

    const SESSION_EXPIRE = 2160000;

    /**
     * controller中执行报错需要回滚的action数组
     * @var array
     */
    public $transactionActions = [];

    public $apiErrMsg = [];

    public $apiData = [];

    protected $isPublic = false;


    public function __construct()
    {
        $this->setCookie();
        if (strpos(request()->getRequestUri(), '/addons/') !== false &&
            strpos(request()->getRequestUri(), '/api.php') !== false
        ) {
            $this->middleware(BasicInformation::class);
        }
    }

    /**
     * 前置action
     */

    public function preAction()
    {
        //是否为商城后台管理路径
        if (config('app.framework') == 'platform') {
            strpos(request()->getRequestUri(), config('app.isWeb')) === 0 && Check::setKey();
        } else {
            strpos(request()->getBaseUrl(), '/web/index.php') === 0 && Check::setKey();
        }
        if (\YunShop::isWeb()) {
            if (!$this->isPublic) {
                PermissionService::validate();
            }
        }
    }

	public function callAction($method, $parameters)
	{
		if (method_exists($this,'preAction')) {
			call_user_func_array([$this, 'preAction'],$parameters);
		}
		// action设置了需要回滚
		if (method_exists($this, 'needTransaction') && $this->needTransaction($method)) {
			return DB::transaction(function() use ($method,$parameters) {
				return parent::callAction($method, $parameters);
			});
		}
		return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
	}

    protected function formatValidationErrors(Validator $validator)
    {
        return $validator->errors()->all();
    }

    /**
     * url参数验证
     *
     * @param array $rules
     * @param Request|null $request
     * @param array $messages
     * @param array $customAttributes
     *
     * @throws AppException
     */
    public function validate(array $rules, Request $request = null, array $messages = [], array $customAttributes = [])
    {
        if (!isset($request)) {
            $request = request();
        }
        $validator = $this->getValidationFactory()->make($request->all(), $rules, $messages, $customAttributes);

        if ($validator->fails()) {
            throw new AppException($validator->errors()->first());
        }
    }

    /**
     * 设置Cookie存储
     *
     * @return void
     */
    protected function setCookie()
    {
		$session_id = request()->cookie(session_name());
        if (!empty($session_id)) {
            $session_id = request()->cookie(session_name());
        }

        if (empty($session_id)) {
            $session_id = md5(\YunShop::app()->uniacid . ':' . random(20));
			Cookie::queue(session_name(),$session_id);

		}

        session_id($session_id);
        Session::factory(\YunShop::app()->uniacid);
    }

    /**
     * 需要回滚
     *
     * @param $action
     *
     * @return bool
     */
    public function needTransaction($action)
    {
        return in_array($action, $this->transactionActions) || in_array('*',
                $this->transactionActions) || $this->transactionActions == '*';
    }

    public function dataIntegrated($data, $flag)
    {
        if ($this->apiErrMsg) {
            return $this->successJson($this->apiErrMsg[0]);
        }

        if (0 == $data['status']) {
            $this->apiErrMsg[] = $data['json'];

            return;
        }

        $this->apiData[$flag] = $data['json'];
    }

    public function checkSingleLogin()
    {
        if (config('app.framework') == 'platform') {
            $loginset = SystemSetting::settingLoad('loginset', 'system_loginset');
            if($loginset['single_login'] == 1)
            {
                $user = \Auth::guard('admin')->user();
                if(session('login_token') != $user->login_token)
                {
                    \Auth::guard('admin')->logout();
                    request()->session()->flush();
                    request()->session()->regenerate();

                    Utils::removeUniacid();

                    redirect('/');
                }
            }
        }
    }

}
