<?php
/**
 * Created by PhpStorm.
 *
 *
 *
 * Date: 2021/12/8
 * Time: 10:15
 */

namespace app\frontend\modules\order\payment\setting;


class ConfirmSetting extends \app\common\payment\setting\other\ConfirmSetting
{
    public function canUse()
    {

        if ($this->paymentTypes->getOrderPay()) {

            return bccomp($this->paymentTypes->getOrderPay()->amount, 0,2) === 0;
        }

        return parent::canUse(); // TODO: Change the autogenerated stub
    }
}