<?php
/****************************************************************
 * Author:  libaojia
 * Date:    2017/12/29 下午3:40
 * Email:   livsyitian@163.com
 * QQ:      995265288
 * User:
 ****************************************************************/

namespace app\backend\modules\member\controllers;


use app\backend\modules\member\models\Member;
use app\backend\modules\member\models\MemberAddress;
use app\common\components\BaseController;
use app\frontend\repositories\MemberAddressRepository;

class MemberAddressController extends BaseController
{
    private $memberAddressRepository;

    public function preAction()
    {
        parent::preAction(); // TODO: Change the autogenerated stub
        $this->memberAddressRepository = app(MemberAddressRepository::class);

    }

    public function index()
    {
        return view('member.address.records', [])->render();
    }
    public function show()
    {
        $addressList = $this->memberAddressRepository->getAddressList($this->getMemberId());

        return $this->successJson('ok', [
            'member' => $this->getMemberModel(),
            'address' => $addressList,
            'is_street' => \Setting::get('shop.trade.is_street')
        ]);
    }

    private function getMemberModel()
    {
        return Member::select('uid', 'nickname', 'realname', 'mobile', 'avatar')
//            ->with('address')
            ->where('uid', $this->getMemberId())
            ->first();
    }


    private function getMemberId()
    {
        return trim(\YunShop::request()->member_id);
    }

}
